export type PermissionRisk = 'low' | 'medium' | 'high';
export type PermissionLevel = 'read' | 'standard' | 'full';
export type PermissionModuleKey =
  | 'business'
  | 'users'
  | 'catalog'
  | 'stock'
  | 'sales'
  | 'customers'
  | 'purchases'
  | 'reports'
  | 'system';

export type PermissionCatalogEntry = {
  code: string;
  module: PermissionModuleKey;
  labelKey: string;
  descriptionKey: string;
  risk: PermissionRisk;
  level: PermissionLevel;
};

export const PERMISSION_MODULES: Array<{
  key: PermissionModuleKey;
  labelKey: string;
}> = [
  { key: 'business', labelKey: 'permissionModules.business' },
  { key: 'users', labelKey: 'permissionModules.users' },
  { key: 'catalog', labelKey: 'permissionModules.catalog' },
  { key: 'stock', labelKey: 'permissionModules.stock' },
  { key: 'sales', labelKey: 'permissionModules.sales' },
  { key: 'customers', labelKey: 'permissionModules.customers' },
  { key: 'purchases', labelKey: 'permissionModules.purchases' },
  { key: 'reports', labelKey: 'permissionModules.reports' },
  { key: 'system', labelKey: 'permissionModules.system' },
];

export const PERMISSION_CATALOG: PermissionCatalogEntry[] = [
  {
    code: 'business.read',
    module: 'business',
    labelKey: 'businessRead',
    descriptionKey: 'businessRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'business.update',
    module: 'business',
    labelKey: 'businessUpdate',
    descriptionKey: 'businessUpdate',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'business.delete',
    module: 'business',
    labelKey: 'businessDelete',
    descriptionKey: 'businessDelete',
    risk: 'high',
    level: 'full',
  },
  {
    code: 'settings.read',
    module: 'business',
    labelKey: 'settingsRead',
    descriptionKey: 'settingsRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'settings.write',
    module: 'business',
    labelKey: 'settingsWrite',
    descriptionKey: 'settingsWrite',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'subscription.read',
    module: 'business',
    labelKey: 'subscriptionRead',
    descriptionKey: 'subscriptionRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'subscription.request',
    module: 'business',
    labelKey: 'subscriptionRequest',
    descriptionKey: 'subscriptionRequest',
    risk: 'high',
    level: 'full',
  },
  {
    code: 'users.read',
    module: 'users',
    labelKey: 'usersRead',
    descriptionKey: 'usersRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'users.create',
    module: 'users',
    labelKey: 'usersCreate',
    descriptionKey: 'usersCreate',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'users.update',
    module: 'users',
    labelKey: 'usersUpdate',
    descriptionKey: 'usersUpdate',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'users.deactivate',
    module: 'users',
    labelKey: 'usersDeactivate',
    descriptionKey: 'usersDeactivate',
    risk: 'high',
    level: 'full',
  },
  {
    code: 'roles.read',
    module: 'users',
    labelKey: 'rolesRead',
    descriptionKey: 'rolesRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'roles.create',
    module: 'users',
    labelKey: 'rolesCreate',
    descriptionKey: 'rolesCreate',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'roles.update',
    module: 'users',
    labelKey: 'rolesUpdate',
    descriptionKey: 'rolesUpdate',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'catalog.read',
    module: 'catalog',
    labelKey: 'catalogRead',
    descriptionKey: 'catalogRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'catalog.write',
    module: 'catalog',
    labelKey: 'catalogWrite',
    descriptionKey: 'catalogWrite',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'price-lists.manage',
    module: 'catalog',
    labelKey: 'priceListsManage',
    descriptionKey: 'priceListsManage',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'stock.read',
    module: 'stock',
    labelKey: 'stockRead',
    descriptionKey: 'stockRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'stock.write',
    module: 'stock',
    labelKey: 'stockWrite',
    descriptionKey: 'stockWrite',
    risk: 'high',
    level: 'full',
  },
  {
    code: 'transfers.read',
    module: 'stock',
    labelKey: 'transfersRead',
    descriptionKey: 'transfersRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'transfers.write',
    module: 'stock',
    labelKey: 'transfersWrite',
    descriptionKey: 'transfersWrite',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'shifts.open',
    module: 'stock',
    labelKey: 'shiftsOpen',
    descriptionKey: 'shiftsOpen',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'shifts.close',
    module: 'stock',
    labelKey: 'shiftsClose',
    descriptionKey: 'shiftsClose',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'sales.read',
    module: 'sales',
    labelKey: 'salesRead',
    descriptionKey: 'salesRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'sales.write',
    module: 'sales',
    labelKey: 'salesWrite',
    descriptionKey: 'salesWrite',
    risk: 'high',
    level: 'full',
  },
  {
    code: 'sales.credit.create',
    module: 'sales',
    labelKey: 'salesCreditCreate',
    descriptionKey: 'salesCreditCreate',
    risk: 'high',
    level: 'full',
  },
  {
    code: 'sales.credit.settle',
    module: 'sales',
    labelKey: 'salesCreditSettle',
    descriptionKey: 'salesCreditSettle',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'sales.return.without-receipt',
    module: 'sales',
    labelKey: 'salesReturnWithoutReceipt',
    descriptionKey: 'salesReturnWithoutReceipt',
    risk: 'high',
    level: 'full',
  },
  {
    code: 'customers.read',
    module: 'customers',
    labelKey: 'customersRead',
    descriptionKey: 'customersRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'customers.create',
    module: 'customers',
    labelKey: 'customersCreate',
    descriptionKey: 'customersCreate',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'customers.update',
    module: 'customers',
    labelKey: 'customersUpdate',
    descriptionKey: 'customersUpdate',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'customers.export',
    module: 'customers',
    labelKey: 'customersExport',
    descriptionKey: 'customersExport',
    risk: 'high',
    level: 'full',
  },
  {
    code: 'customers.sensitive.read',
    module: 'customers',
    labelKey: 'customersSensitiveRead',
    descriptionKey: 'customersSensitiveRead',
    risk: 'high',
    level: 'full',
  },
  {
    code: 'customers.anonymize',
    module: 'customers',
    labelKey: 'customersAnonymize',
    descriptionKey: 'customersAnonymize',
    risk: 'high',
    level: 'full',
  },
  {
    code: 'purchases.read',
    module: 'purchases',
    labelKey: 'purchasesRead',
    descriptionKey: 'purchasesRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'purchases.write',
    module: 'purchases',
    labelKey: 'purchasesWrite',
    descriptionKey: 'purchasesWrite',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'suppliers.read',
    module: 'purchases',
    labelKey: 'suppliersRead',
    descriptionKey: 'suppliersRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'suppliers.write',
    module: 'purchases',
    labelKey: 'suppliersWrite',
    descriptionKey: 'suppliersWrite',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'attachments.write',
    module: 'purchases',
    labelKey: 'attachmentsWrite',
    descriptionKey: 'attachmentsWrite',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'expenses.read',
    module: 'purchases',
    labelKey: 'expensesRead',
    descriptionKey: 'expensesRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'expenses.write',
    module: 'purchases',
    labelKey: 'expensesWrite',
    descriptionKey: 'expensesWrite',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'reports.read',
    module: 'reports',
    labelKey: 'reportsRead',
    descriptionKey: 'reportsRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'exports.write',
    module: 'reports',
    labelKey: 'exportsWrite',
    descriptionKey: 'exportsWrite',
    risk: 'high',
    level: 'full',
  },
  {
    code: 'audit.read',
    module: 'reports',
    labelKey: 'auditRead',
    descriptionKey: 'auditRead',
    risk: 'high',
    level: 'full',
  },
  {
    code: 'approvals.read',
    module: 'system',
    labelKey: 'approvalsRead',
    descriptionKey: 'approvalsRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'approvals.write',
    module: 'system',
    labelKey: 'approvalsWrite',
    descriptionKey: 'approvalsWrite',
    risk: 'high',
    level: 'full',
  },
  {
    code: 'notifications.read',
    module: 'system',
    labelKey: 'notificationsRead',
    descriptionKey: 'notificationsRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'offline.read',
    module: 'system',
    labelKey: 'offlineRead',
    descriptionKey: 'offlineRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'offline.write',
    module: 'system',
    labelKey: 'offlineWrite',
    descriptionKey: 'offlineWrite',
    risk: 'high',
    level: 'full',
  },
  {
    code: 'search.read',
    module: 'system',
    labelKey: 'searchRead',
    descriptionKey: 'searchRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'notes.read',
    module: 'system',
    labelKey: 'notesRead',
    descriptionKey: 'notesRead',
    risk: 'low',
    level: 'read',
  },
  {
    code: 'notes.write',
    module: 'system',
    labelKey: 'notesWrite',
    descriptionKey: 'notesWrite',
    risk: 'medium',
    level: 'standard',
  },
  {
    code: 'notes.manage',
    module: 'system',
    labelKey: 'notesManage',
    descriptionKey: 'notesManage',
    risk: 'high',
    level: 'full',
  },
];
