'use client';

import { useState } from 'react';
import { useTranslations } from 'next-intl';
import { notify } from '@/components/notifications/NotificationProvider';
import { usePdfRegistry, type SectionPdfPayload } from './pdf-context';
import type { ReportPdfMeta } from './ReportPdfDocument';

type Props = {
  buildMeta: () => ReportPdfMeta;
  /** Order in which sections should appear in the PDF. */
  sectionOrder: { id: string; label: string }[];
  /** Suggested filename (without extension). */
  filename: string;
};

export function ExportPdfButton({ buildMeta, sectionOrder, filename }: Props) {
  const t = useTranslations('reports');
  const [busy, setBusy] = useState(false);
  const { snapshot } = usePdfRegistry();

  const handleClick = async () => {
    if (busy) return;
    setBusy(true);
    try {
      const meta = buildMeta();
      const registry = snapshot();
      const sections = sectionOrder
        .map(({ id, label }) => {
          const payload = registry.get(id);
          return payload ? { id, label, payload } : null;
        })
        .filter((s): s is { id: string; label: string; payload: SectionPdfPayload } =>
          Boolean(s),
        );

      // Lazy-load PDF deps to keep them out of the initial Reports bundle.
      const [{ pdf }, { ReportPdfDocument }] = await Promise.all([
        import('@react-pdf/renderer'),
        import('./ReportPdfDocument'),
      ]);

      const labels = {
        eyebrow: t('eyebrow'),
        period: t('period') ?? 'Period',
        branch: t('branch') ?? 'Branch',
        generated: t('generated') ?? 'Generated',
        kpisHeading: t('kpisHeading') ?? 'Key metrics',
        breakdownsHeading: t('breakdownsHeading') ?? 'Breakdowns',
        tablesHeading: t('tablesHeading') ?? 'Detail',
        footer: t('pdfFooter') ?? 'Generated by New Vision Inventory',
        page: t('page') ?? 'Page',
        of: t('of') ?? 'of',
        empty: t('noData') ?? 'No data',
      };

      const blob = await pdf(
        <ReportPdfDocument meta={meta} sections={sections} labels={labels} />,
      ).toBlob();

      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${filename}.pdf`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(url);

      notify.success(t('pdfExported') ?? 'PDF downloaded');
    } catch (err) {
      console.warn('PDF export failed', err);
      notify.error(t('pdfExportFailed') ?? 'PDF export failed');
    } finally {
      setBusy(false);
    }
  };

  return (
    <button
      type="button"
      className="rpt-export-pdf"
      onClick={handleClick}
      disabled={busy}
      aria-busy={busy}
    >
      {busy
        ? (t('pdfExporting') ?? 'Exporting…')
        : (t('exportPdf') ?? 'Export PDF')}
    </button>
  );
}
